name: Deploy to AWS EKS (Multi-Arch)

on:
  push:
    branches: [ main ]

env:
  IMAGE_REPO: my-simple-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout your source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 — Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4 — Login to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # Step 5 — Build and push multi-arch Docker image
      - name: Build and push Docker image (multi-arch)
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          IMAGE_TAG=${{ github.sha }}
          # Strip newlines/whitespace from ECR registry secret
          ECR_REGISTRY=$(echo "${{ secrets.ECR_REGISTRY }}" | tr -d '\n' | tr -d '\r')
          IMAGE_NAME="${ECR_REGISTRY}/${{ env.IMAGE_REPO }}:$IMAGE_TAG"
          LATEST_NAME="${ECR_REGISTRY}/${{ env.IMAGE_REPO }}:latest"
          echo "Building image: $IMAGE_NAME"
          docker buildx build --platform linux/amd64,linux/arm64 -t "$IMAGE_NAME" -t "$LATEST_NAME" --push .

      # Step 6 — Update kubeconfig for EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      # Step 7 — Deploy new image to EKS
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY="${{ secrets.ECR_REGISTRY }}"
          IMAGE_NAME="${ECR_REGISTRY}/${{ env.IMAGE_REPO }}:$IMAGE_TAG"
          kubectl set image deployment/my-simple-app \
            my-simple-app="$IMAGE_NAME" --record
          kubectl rollout status deployment/my-simple-app
